name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Render docker-compose
        run: |
          sed "s/{{TAG}}/${GITHUB_REF##*/}/g" \
            .github/templates/docker-compose.template.yml \
            > docker-compose.yml

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: docker-compose.yml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
